# Generated by Django 4.1.1 on 2022-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='coffee',
            name='ratings',
            field=models.ManyToManyField(to='main_app.rating'),
        ),
    ]
